TT#116101 scenarios/invite_sdp_filter: fix sdp in 200OK reply
Even if the video support is disabed by the callee, a codec has to be
provided in the reply. Addin coded 34 equel to the one received in the
initial INVITE.

The missing codec was causing SEMS to add an empty line after the
sdp m= line causing rtpengine to return:
error: Failed to parse SDP

Change-Id: I80227c9dd9a34a21b278d9b069d5af88eb504655