TT#81700 set_config.sh: create log dir before pid_watcher execution
> Traceback (most recent call last):
>  File "/usr/local/devel/kamailio-config-tests/bin/pid_watcher.py", line 33, in <module>
>    logging.basicConfig(
>  File "/usr/lib/python3.9/logging/__init__.py", line 1999, in basicConfig
>    h = FileHandler(filename, mode,
>  File "/usr/lib/python3.9/logging/__init__.py", line 1142, in __init__
>    StreamHandler.__init__(self, self._open())
>  File "/usr/lib/python3.9/logging/__init__.py", line 1171, in _open
>    return open(self.baseFilename, self.mode, encoding=self.encoding,
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/devel/kamailio-config-tests/log/pid_watcher.log'

Change-Id: I79b520ff3ee58d0e53a81c59ac263d3018f9a190
(cherry picked from commit 95c40ce9fbd0f16417607604dbc231e9a9537944)
(cherry picked from commit 6f6f84808a843889aaf2e14ea08236f76ce4a134)